/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : Role,
  'language' : IDL.Text,
  'timestamp' : Time,
});
export const UserPreferences = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'voiceEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'clearConversationHistory' : IDL.Func([], [], []),
  'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'saveKnowledgeEntry' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'saveMessage' : IDL.Func([IDL.Text, IDL.Text, Role], [Message], []),
  'setUserPreferences' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : Role,
    'language' : IDL.Text,
    'timestamp' : Time,
  });
  const UserPreferences = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'voiceEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'clearConversationHistory' : IDL.Func([], [], []),
    'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'saveKnowledgeEntry' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'saveMessage' : IDL.Func([IDL.Text, IDL.Text, Role], [Message], []),
    'setUserPreferences' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };